AWSTemplateFormatVersion: 2010-09-09
Description: Sets up ecs service
Parameters:
  ClusterName:
    Description: Cluster name
    Type: String
    Default: stone

  SiteTasksNumber:
    Description: Site tasks number
    Default: 1
    Type: Number

  SiteContainerMemorySize:
    Description: Site container memory size
    Type: Number
    Default: 128

  DockerImage:
    Description: Docker image
    Type: String
    Default: 599405637292.dkr.ecr.us-west-1.amazonaws.com/stone:latest

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        'Fn::ImportValue': !Sub ${ClusterName}VPC
      Protocol: HTTP
      Port: 3000
      Matcher:
          HttpCode: '200,301,401,302'
      HealthCheckIntervalSeconds: 40
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
        - Key: stickiness.enabled
          Value: true

  SiteTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: stone-elb-site
      ContainerDefinitions:
        - Name: stone-elb-site
          Image: !Ref DockerImage
          PortMappings:
            - ContainerPort: 3000
              HostPort: 0
          MemoryReservation: !Ref SiteContainerMemorySize

  SiteService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: stone
      Role: 'arn:aws:iam::599405637292:role/us-west-1-stone_ECSRole'
      TaskDefinition: !Ref SiteTask
      DesiredCount: !Ref SiteTasksNumber
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 100
      LoadBalancers:
        - ContainerName: stone-elb-site
          ContainerPort: 3010
          TargetGroupArn: !Ref TargetGroup
          #TargetGroupArn: 'arn:aws:elasticloadbalancing:us-west-1:599405637292:targetgroup/stone-default/efb5fd11a1b94196'